<?php

// Written by `php artisan app:generate-example-shots`. Do not edit by hand: run the command.
// The pictures /examples shows: each demo schedule's own header and logo at the size the wall
// uses (art), and the photographs of their pages with what was measured on them (shots, xray).

return [
    'taken' => '2026-10-09',
    'art' => [
        'meditationclasses' => [
            'header' => 'wall-meditationclasses.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-meditationclasses.webp',
        ],
        'weekendyogaretreat' => [
            'header' => 'wall-weekendyogaretreat.webp',
            'w' => 1040,
            'h' => 381,
            'logo' => 'logo-weekendyogaretreat.webp',
        ],
        'hikingclub' => [
            'header' => 'wall-hikingclub.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-hikingclub.webp',
        ],
        'battleofthebands' => [
            'header' => 'wall-battleofthebands.webp',
            'w' => 1040,
            'h' => 693,
            'logo' => 'logo-battleofthebands.webp',
        ],
        'sufficientgroundscoffeemusic' => [
            'header' => 'wall-sufficientgroundscoffeemusic.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-sufficientgroundscoffeemusic.webp',
        ],
        'villageidiot' => [
            'header' => 'wall-villageidiot.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-villageidiot.webp',
        ],
        'communityyouthgroup' => [
            'header' => 'wall-communityyouthgroup.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-communityyouthgroup.webp',
        ],
        'karateclub' => [
            'header' => 'wall-karateclub.webp',
            'w' => 1040,
            'h' => 693,
            'logo' => 'logo-karateclub.webp',
        ],
        'countyfairgrounds' => [
            'header' => 'wall-countyfairgrounds.webp',
            'w' => 959,
            'h' => 364,
            'logo' => 'logo-countyfairgrounds.webp',
        ],
        'nateswoodworkingshop' => [
            'header' => 'wall-nateswoodworkingshop.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-nateswoodworkingshop.webp',
        ],
        'painting' => [
            'header' => 'wall-painting.webp',
            'w' => 1040,
            'h' => 244,
            'logo' => 'logo-painting.webp',
        ],
        'pagesbooknookshop' => [
            'header' => 'wall-pagesbooknookshop.webp',
            'w' => 1040,
            'h' => 520,
            'logo' => 'logo-pagesbooknookshop.webp',
        ],
        'simpsons' => [
            'header' => 'wall-simpsons.webp',
            'w' => 1040,
            'h' => 347,
            'logo' => 'logo-simpsons.webp',
        ],
        'demo-moestavern' => [
            'header' => 'wall-demo-moestavern.webp',
            'w' => 1040,
            'h' => 347,
            'logo' => 'logo-demo-moestavern.webp',
        ],
        'demo-amphitheater' => [
            'header' => 'wall-demo-amphitheater.webp',
            'w' => 1040,
            'h' => 347,
            'logo' => 'logo-demo-amphitheater.webp',
        ],
        'demo-bowlarama' => [
            'header' => 'wall-demo-bowlarama.webp',
            'w' => 1040,
            'h' => 347,
            'logo' => 'logo-demo-bowlarama.webp',
        ],
        'demo-aztectheater' => [
            'header' => 'wall-demo-aztectheater.webp',
            'w' => 1040,
            'h' => 347,
            'logo' => 'logo-demo-aztectheater.webp',
        ],
        'demo-lardlad' => [
            'header' => 'wall-demo-lardlad.webp',
            'w' => 1040,
            'h' => 347,
            'logo' => 'logo-demo-lardlad.webp',
        ],
    ],
    'shots' => [
        'meditationclasses' => [
            'full' => [
                'file' => 'meditationclasses.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Meditation Classes',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 211.0,
                'h' => 80.0,
            ],
            'glow' => '103 149 230',
        ],
        'weekendyogaretreat' => [
            'full' => [
                'file' => 'weekendyogaretreat.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Monthly Yoga Retreat',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 182.3,
                'h' => 80.0,
            ],
            'glow' => '14 154 198',
        ],
        'hikingclub' => [
            'full' => [
                'file' => 'hikingclub.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Tri-Rivers Hiking Club',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 229.0,
                'h' => 80.0,
            ],
            'glow' => '116 75 198',
        ],
        'battleofthebands' => [
            'full' => [
                'file' => 'battleofthebands.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Battle of the Bands!',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 287.3,
                'h' => 80.0,
            ],
            'glow' => '39 128 198',
        ],
        'sufficientgroundscoffeemusic' => [
            'full' => [
                'file' => 'sufficientgroundscoffeemusic.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Sufficient Grounds Cafe',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 229.0,
                'h' => 80.0,
            ],
            'glow' => '198 95 62',
        ],
        'villageidiot' => [
            'full' => [
                'file' => 'villageidiot.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Village Idiot Blues & Jazz',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 229.0,
                'h' => 80.0,
            ],
            'glow' => '83 140 198',
        ],
        'communityyouthgroup' => [
            'full' => [
                'file' => 'communityyouthgroup.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Community Youth Group',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 229.0,
                'h' => 80.0,
            ],
            'glow' => '89 134 198',
        ],
        'karateclub' => [
            'full' => [
                'file' => 'karateclub.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Community Karate Club',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 287.3,
                'h' => 80.0,
            ],
            'glow' => '198 135 88',
        ],
        'countyfairgrounds' => [
            'full' => [
                'file' => 'countyfairgrounds.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'County Fair Grounds',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 186.8,
                'h' => 80.0,
            ],
            'glow' => '201 27 37',
        ],
        'nateswoodworkingshop' => [
            'full' => [
                'file' => 'nateswoodworkingshop.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Nate\'s Woodworking Classes',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 229.0,
                'h' => 80.0,
            ],
            'glow' => '198 154 89',
        ],
        'painting' => [
            'full' => [
                'file' => 'painting.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Weekly Oil Painting Masterclass',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 136.0,
                'h' => 80.0,
            ],
            'glow' => '198 81 58',
        ],
        'pagesbooknookshop' => [
            'full' => [
                'file' => 'pagesbooknookshop.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Page\'s Book Nook',
                'font' => 'Roboto',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 229.0,
                'h' => 80.0,
            ],
            'glow' => '198 97 74',
        ],
        'simpsons' => [
            'full' => [
                'file' => 'simpsons.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'The Simpsons - Springfield Events',
                'font' => 'Bangers',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
            ],
            'glow' => '237 212 28',
        ],
        'demo-moestavern' => [
            'full' => [
                'file' => 'demo-moestavern.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Moe\'s Tavern',
                'font' => 'Alfa Slab One',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
            ],
            'glow' => '198 139 24',
        ],
        'demo-amphitheater' => [
            'full' => [
                'file' => 'demo-amphitheater.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Springfield Amphitheater',
                'font' => 'Concert One',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
            ],
            'glow' => '30 143 235',
        ],
        'demo-bowlarama' => [
            'full' => [
                'file' => 'demo-bowlarama.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Barney\'s Bowl-A-Rama',
                'font' => 'Bowlby One',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
            ],
            'glow' => '198 90 38',
        ],
        'demo-aztectheater' => [
            'full' => [
                'file' => 'demo-aztectheater.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'The Aztec Theater',
                'font' => 'Josefin Sans',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
            ],
            'glow' => '199 135 33',
        ],
        'demo-lardlad' => [
            'full' => [
                'file' => 'demo-lardlad.webp',
                'h' => 1640.0,
                'pw' => 780,
                'ph' => 3280,
            ],
            'title' => [
                'x' => 44.0,
                'w' => 302.0,
                'text' => 'Lard Lad Donuts',
                'font' => 'Fredoka One',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
            ],
            'glow' => '242 101 164',
        ],
    ],
    'xray' => [
        'xr-desk-home' => [
            'file' => 'xr-desk-home.webp',
            'w' => 1280,
            'h' => 1500,
            'pw' => 1600,
            'ph' => 1875,
            'pins' => [
                'chips' => [
                    'x' => 274,
                    'y' => 427,
                    'w' => 88,
                    'h' => 36,
                ],
                'fan' => [
                    'x' => 256,
                    'y' => 865,
                    'w' => 117,
                    'h' => 34,
                ],
                'follow' => [
                    'x' => 780,
                    'y' => 218,
                    'w' => 88,
                    'h' => 44,
                ],
                'layout' => [
                    'x' => 936,
                    'y' => 218,
                    'w' => 88,
                    'h' => 44,
                ],
                'lineup' => [
                    'x' => 256,
                    'y' => 805,
                    'w' => 454,
                    'h' => 32,
                ],
            ],
            'title' => [
                'text' => 'Moe\'s Tavern',
                'font' => 'Alfa Slab One',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 166.0,
                'h' => 40.0,
                'align' => 'start',
                'x' => 256.0,
                'w' => 768.0,
            ],
        ],
        'xr-phone-home' => [
            'file' => 'xr-phone-home.webp',
            'w' => 390,
            'h' => 1500,
            'pw' => 585,
            'ph' => 2250,
            'pins' => [
                'chips' => [
                    'x' => 22,
                    'y' => 537,
                    'w' => 88,
                    'h' => 36,
                ],
                'follow' => [
                    'x' => 203,
                    'y' => 278,
                    'w' => 88,
                    'h' => 44,
                ],
            ],
            'title' => [
                'text' => 'Moe\'s Tavern',
                'font' => 'Alfa Slab One',
                'size' => 32.0,
                'weight' => 600,
                'color' => 'rgb(21, 27, 38)',
                'y' => 150.0,
                'h' => 80.0,
                'align' => 'center',
                'x' => 44.0,
                'w' => 302.0,
            ],
        ],
        'xr-phone-event' => [
            'file' => 'xr-phone-event.webp',
            'w' => 390,
            'h' => 3100,
            'pw' => 585,
            'ph' => 4650,
            'pins' => [
                'calendar' => [
                    'x' => 20,
                    'y' => 2752,
                    'w' => 192,
                    'h' => 48,
                ],
                'lineup' => [
                    'x' => 20,
                    'y' => 1979,
                    'w' => 228,
                    'h' => 28,
                ],
                'tickets' => [
                    'x' => 80,
                    'y' => 3036,
                    'w' => 290,
                    'h' => 52,
                ],
                'weekly' => [
                    'x' => 104,
                    'y' => 519,
                    'w' => 160,
                    'h' => 20,
                ],
            ],
        ],
    ],
];
