<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Auto-Generated Blog Post Review</title>
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
    <div style="background-color: #f59e0b; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 24px;">Auto-Generated Blog Post</h1>
    </div>

    <div style="background-color: #fef3c7; padding: 15px; border-left: 4px solid #f59e0b; margin: 0;">
        <p style="margin: 0; font-weight: bold; color: #92400e;">This blog post was automatically generated by AI and published. Please review it for accuracy and quality.</p>
    </div>

    <div style="background-color: #f9f9f9; padding: 20px; border-radius: 0 0 8px 8px;">
        <div style="background-color: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #4E81FA;">
            <h2 style="margin-top: 0; color: #4E81FA;">{{ $blogPost->title }}</h2>

            @if($blogPost->excerpt)
            <p style="margin: 10px 0; font-style: italic; color: #666;">{{ $blogPost->excerpt }}</p>
            @endif

            @if($blogPost->tags && count($blogPost->tags) > 0)
            <p style="margin: 10px 0;">
                <strong>Tags:</strong>
                @foreach($blogPost->tags as $tag)
                    <span style="display: inline-block; background-color: #e5e7eb; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-right: 5px;">{{ $tag }}</span>
                @endforeach
            </p>
            @endif
        </div>

        <div style="background-color: white; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #4E81FA;">Content Preview</h3>
            <div style="color: #555; white-space: pre-wrap;">{{ $truncatedContent }}</div>
        </div>

        <div style="text-align: center; margin: 30px 0;">
            <a href="{{ $viewUrl }}"
               style="display: inline-block; background-color: #4E81FA; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; font-size: 16px; margin: 5px;">
                View Full Post
            </a>

            <a href="{{ $editUrl }}"
               style="display: inline-block; background-color: #6b7280; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; font-size: 16px; margin: 5px;">
                Edit Post
            </a>
        </div>

        <div style="background-color: #fef2f2; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #dc2626; text-align: center;">
            <h3 style="margin-top: 0; color: #dc2626;">Delete This Post</h3>
            <p style="color: #7f1d1d; margin-bottom: 15px;">If this post is inappropriate or low quality, you can delete it immediately.</p>
            <a href="{{ $deleteUrl }}"
               style="display: inline-block; background-color: #dc2626; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; font-weight: bold; font-size: 16px;">
                Delete This Post
            </a>
            <p style="font-size: 12px; color: #999; margin-top: 15px;">This delete link expires in 7 days.</p>
        </div>

        <p style="font-size: 12px; color: #999; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 20px;">
            This is an automated notification from Event Schedule.
        </p>
    </div>
</body>
</html>
