Auto-Generated Blog Post

This blog post was automatically generated by AI and published. Please review it for accuracy and quality.

{{ $blogPost->title }}

@if($blogPost->excerpt)
{{ $blogPost->excerpt }}
@endif

@if($blogPost->tags && count($blogPost->tags) > 0)
Tags: {{ implode(', ', $blogPost->tags) }}
@endif

Content Preview:
{{ $truncatedContent }}

View Full Post: {{ $viewUrl }}

Edit Post: {{ $editUrl }}

Delete This Post: {{ $deleteUrl }}
(If this post is inappropriate or low quality, you can delete it immediately. This delete link expires in 7 days.)

This is an automated notification from Event Schedule.
